### ISSUE TITLE
InvalidArgument: allLinks scope must be valid ([page, domain] to [page, subdomain, domain])

### ISSUE THREAD

**Issue by martyMM** [seomoz/linkscape-gem#1]
When I run this command:

response = client.allLinks("www.google.com", :domain, :urlcols => [:title, :url, :page_authority, :domain_authority], :linkcols => :all, :filters => :external, :limit => 3, :scope => :page_to_domain)

I get the following error:

InvalidArgument: allLinks scope must be valid ([page, domain] to [page, subdomain, domain])
from /home/marty/.rvm/gems/ruby-1.9.2-p136/gems/linkscape-0.3.0/lib/linkscape/client.rb:87:in `allLinks'

As far as I can tell, the scope is entered correctly. I've also tried every possible combination listed in the documentation. I cant figure out why this is returning an error. Possible bug?

**Comment by tithonium** [comment]
The argument parser looks for a hash as the last argument, but then - in the case of allLinks - if the number of arguments is >=2, it will take the second and third arguments as the scope, and ignore the scope in the options hash.

So, by passing the :domain argument after google.com, you're specifying a scope of "domain_to_". Try this and I bet it'll work:

response = client.allLinks("www.google.com", :urlcols => [:title, :url, :page_authority, :domain_authority], :linkcols => :all, :filters => :external, :limit => 3, :scope => :page_to_domain)

**Comment by martyMM** [comment]
Yep, that worked! Thanks!

**Comment by bradical** [comment]
> So, by passing the :domain argument after google.com, you're specifying a scope of "domain to"

Not sure I understand this. [From the documentation](https://github.com/seomoz/linkscape-gem) it appears like the second argument is specifying whether you're looking for links to the whole URI (page), the subdomain or the domain of the passed URI. Is that not correct? Is there a way to do this AND pass `:page` as the second argument? Seems like it's more like saying "... to [page, subdomain, domain]" when you use the second param, no?
