### ISSUE TITLE
InvalidArgument: allLinks scope must be valid ([page, domain] to [page, subdomain, domain])

### ISSUE THREAD

**Issue by davidhq** [seomoz/linkscape-gem#6]
This is really strange how it's implemented....

When I use:
client.allLinks(uri, :page, :urlcols => [:title, :url, :page_authority, :domain_authority], :linkcols => :all, :filters => :external, :limit => 3, :scope => :page_to_domain)

I still get the message... I went to check the code and it doesn't really make sense to me... 

scope = args.length >= 2 ? "#{args.shift}_to_#{args.shift}" : (args.first ? args.shift : options[:scope])

why would be determining the scope argument be dependent on the number of arguments and this complicated logic? The code thinks that my scope is :page and then throws an exception becaue it's not /^(page|domain)_to_(page|subdomain|domain)$/

I probably don't understand something obvious... and I can't get it to work... please help

**Comment by phs** [comment]
For reference, the line you are talking about appears to be [here](https://github.com/seomoz/linkscape-gem/blob/f7465a9b27ac4b8890a41ee3c56f5421e8f2843e/lib/linkscape/client.rb#L82).

My opinions of the code aside, it is trying to support two separate call styles.  One can either specify everything with explicitly named options, or one can do so with positional parameters.  Mixing them seems to be getting us in trouble.

I suggest you restrict your usage to the named option style.  In particular, something like

```
client.allLinks(
  :url => uri,
  :urlcols => [:title, :url, :page_authority, :domain_authority],
  :linkcols => :all,
  :filters => :external,
  :scope => :page_to_domain,
  :limit => 3
)
```

**Comment by davidhq** [comment]
Thank you! The confusing thing for me was that in the documentation it says:

`client.allLinks(uri, :page, :urlcols => [:title, :url, :page_authority, :domain_authority], :linkcols => :all, :filters => :external, :limit => 3)`

And it doesn't include scope, it's just mentioned below... then I wanted to add that simply by `scope => :page_to_domain` but it returned that exception. Quite confusing ... It also doesn't say anywhere that there are two possibilities of passing parameters.

**Comment by phs** [comment]
That's a bug in our documentation, thank you.  I'll see that it get cleaned up.

**Comment by davidhq** [comment]
great!
